language: node_js
sudo: required

node_js:
  - "7"


before_install:
  - sudo /bin/sh -c 'echo "127.0.0.10 judge.local" >> /etc/hosts'
  - sudo /bin/sh -c 'echo "127.0.0.20 proxy.local" >> /etc/hosts'
  - npm install -g typings
  - typings install

