language: node_js
sudo: required

node_js:
  - "6"

addons:
  apt:
    packages:
    - squid



before_install:
  - sudo /bin/sh -c 'echo "127.0.0.10 judge.local" >> /etc/hosts'
  - sudo /bin/sh -c 'echo "127.0.0.20 proxy.local" >> /etc/hosts'
  - export CI_CONTAINER=1
  - npm install -g nyc
  - npm install -g codecov
  - npm install -g typings
  - typings install

