== Issues

@TASK:{counter:task} 20170518 +
Erweitere JudgeResults um empfangene Header.


@TASK:{counter:task} 20170518 +
Untersuche folgende Meldung, die vom Proxy zurückgeliefert werden können:

* HTTP/1.1 407 Proxy Authentication Required
* HTTP/1.1 502 Bad Gateway


@TASK:{counter:task} 20170607 +
Implementiere den Prozess der eine ausgewählte vordefinierte Routine zum Aktualisieren der
Proxies kontrolliert ausführt

  - Abbruch bei zu langer Verarbeitung
  - Abfangen von unerwarteten Fehlern
  - gefundene Proxyies sammeln


@TASK:{counter:task} 20170620 +minor +
Make the use of other judge server possible and configurable.


[.line-through]#@TASK:{counter:task} 20170620# +minor +
Extend the cli command 'judge' by the file option, to check all given proxies
in the text file. The format should be simple 'ip:port\n'


[.line-through]#@TASK:{counter:task} 20170621 +minor# +
Handle messages from monitor an other components and deliver them immediately
to the present subscriber. Implement an EventBus which allows registered
subscribers to receive events by type or namespace.
```
class Message {...}

class Subscriber {

  @subscribe
  onMessage(Message:m){...}

}

let s = new Subscriber()
EventBus.register(s)

let m = new Message()
EventBus.post(m)
// or
m.post()

```

@TASK:{counter:task} 20170622 +minor +
Redesign the cli output of judge.


@TASK:{counter:task} 20170623 +patch +
Analyse warning on travis:
```
WARNING: executing requirements for [object Object] failed, this types cannot be loaded
```

@TASK:{counter:task} 20170623 +patch +
Extract the validation of proxy lists in JudgeFileCommand to a seperate worker class.

@TASK:{counter:task} 20170623 +
Analyse errors from proxy results and try to simulate them in testcases.

- ETIMEOUT
- ESOCKETTIMEOUT
- further @see Exceptions.handle impl

NOTE: implemented Exceptions.handle to wrap errors to NestedException with error code


[.line-through]#@TASK:{counter:task} 20170623# +minor +
Request over elite proxy cannot be identifiert as proxied. If via or forward
exists, but the ip isn't listed then it is an anonymus proxy.+
Write testcase for the different scoring possibilities.


@TASK:{counter:task} 20170624 +
UserAgent generator, generate combinations of given agent parameter types.


@TASK:{counter:task} 20170626 +
Backlog: Docker test enviroment

@TASK:{counter:task} 20170626 +
Backlog: Internationalization


@TASK:{counter:task} 20170626 +
Backlog: Spin-Offs

- EventBus
- AsyncWorkerQueue


@TASK:{counter:task} 20170626 patch per subtask +
Impl. multiple proxy provider

- http://www.proxy-listen.de
- http://proxydb.net


@TASK:{counter:task} 20170626 minor +
Bootstrap implementation which should handle:

- default config definition
- storage initialisation (data are present in Config)
- ui enabling
- proxyserver enabling



@TASK:{counter:task} 20170627 minor +
Impl. of the processing workflow.

1. fetching proxy ip by provider and transport to the
2. ip filter detects if an ip was already check in last time ()
* validating quality of
** on errors save the ip
* sadf




