== Issues

@TASK:{counter:task} 20170518 +
Erweitere JudgeResults um empfangene Header.


@TASK:{counter:task} 20170518 +
Untersuche folgende Meldung, die vom Proxy zurückgeliefert werden können:

* HTTP/1.1 407 Proxy Authentication Required
* HTTP/1.1 502 Bad Gateway


@TASK:{counter:task} 20170607 +
Implementiere den Prozess der eine ausgewählte vordefinierte Routine zum Aktualisieren der
Proxies kontrolliert ausführt

  - Abbruch bei zu langer Verarbeitung
  - Abfangen von unerwarteten Fehlern
  - gefundene Proxyies sammeln


@TASK:{counter:task} 20170620 +minor +
Make the use of other judge server possible and configurable.


[.line-through]#@TASK:{counter:task} 20170620# +minor +
Extend the cli command 'judge' by the file option, to check all given proxies
in the text file. The format should be simple 'ip:port\n'


[.line-through]#@TASK:{counter:task} 20170621 +minor# +
Handle messages from monitor an other components and deliver them immediately
to the present subscriber. Implement an EventBus which allows registered
subscribers to receive events by type or namespace.
```
class Message {...}

class Subscriber {

  @subscribe
  onMessage(Message:m){...}

}

let s = new Subscriber()
EventBus.register(s)

let m = new Message()
EventBus.post(m)
// or
m.post()

```

@TASK:{counter:task} 20170622 +minor +
Redesign the cli output of judge.


[.line-through]#@TASK:{counter:task} 20170623 +patch# +
Analyse warning on travis:
```
WARNING: executing requirements for [object Object] failed, this types cannot be loaded
```

[.line-through]#@TASK:{counter:task} 20170623 +patch# +
Extract the validation of proxy lists in JudgeFileCommand to a seperate worker class.

@TASK:{counter:task} 20170623 +
Analyse errors from proxy results and try to simulate them in testcases.

- ETIMEOUT
- ESOCKETTIMEOUT
- further @see Exceptions.handle impl

NOTE: implemented Exceptions.handle to wrap errors to NestedException with error code


[.line-through]#@TASK:{counter:task} 20170623# +minor +
Request over elite proxy cannot be identifiert as proxied. If via or forward
exists, but the ip isn't listed then it is an anonymus proxy.+
Write testcase for the different scoring possibilities.


@TASK:{counter:task} 20170624 +
UserAgent generator, generate combinations of given agent parameter types.


@TASK:{counter:task} 20170626 +
Backlog: Docker test enviroment

@TASK:{counter:task} 20170626 +
Backlog: Internationalization


@TASK:{counter:task} 20170626 +
Backlog: Spin-Offs

- EventBus
- AsyncWorkerQueue


@TASK:{counter:task} 20170626 patch per subtask +
Impl. multiple proxy provider

- http://www.proxy-listen.de
- http://proxydb.net


@TASK:{counter:task} 20170626 minor +
Bootstrap implementation which should handle:

- default config definition
- storage initialisation (data are present in Config)
- ui enabling
- proxyserver enabling


[.line-through]#@TASK:{counter:task} 20170627 minor# +
Impl. of the processing workflow.

1. fetching proxy ip by provider and transport to the ip filter
2. ip filter detects if an ip was already check in last time and
decides if it should be (re)validated or not
3. the validator checks the quality of the proxy and saves the results
to the database

@TASK:{counter:task} 20170706 minor +
Impl. the server part which will deliver information via rest services
for a coming ui or other

* runtime statistics
** started / running since
** proxy count all/active/inactive
* fetcher statistics
** show last execution for each fetch job
** count found proxies
** manuel control (start, stop, disable?)
* proxies
** get next in line fastes proxy (for )
** list proxy queue
** search by country, speed, level, etc.

[.line-through]#@TASK:{counter:task} 20170706 minor# +
Impl. configurable winston logger and define the
configuration parameter

@TASK:{counter:task} 20170707 minor +
Fetcher control in configuration? Define if some fetcher should be
excluded.

[.line-through]#@TASK:{counter:task} 20170707 minor# +
Impl. ProviderManager

* schedule fetcher
** make this configurable (offset)
* fetcher statistics
** count proxies / new / existing

@TASK:{counter:task} 20170708 +
Write documentation for the configuration possible configuration
settings.

@TASK:{counter:task} 20170709 +
Add docker support

[.line-through]#@TASK:{counter:task} 20170709# +
update commons-config
```
// set options and return them
options = Config.set(key, options)

// get fallback values
options = Config.get(key, fallback)

// get all config settings
options = Config.all()

// save options in 'config_options' namespace
options = Config.options(...)

// file settings in options, if base file doesn't
// exists then ignore it.
// If interpolation doesn't work then also ignore the entry.
Config.options({
        configs: [
            {type: 'system'},
            {type: 'file', file: '${argv.configfile}'},
        ]
    });

```


@TASK:{counter:task} 20170709 +
Exception
```
{ Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: npb_ip_loc.ip
    at Error (native) errno: 19, code: 'SQLITE_CONSTRAINT' }
```

@TASK:{counter:task} 20170714 +
API

* start / stop
* delete long broken proxies (cleanup)
* add new proxy(-ies)
* delete single or mark as deleted
* list be criteria
* search by criteria
* force re-validation


[.line-through]#@TASK:{counter:task} 20170715# +
Rename: +
 ProxyDataSelector => ProxyFilter +
 ProxyValidationController => ProxyValidator +
 ProxyDataValidateEvent => ProxyValidateEvent


[.line-through]##@TASK:{counter:task} 20170715 +vminor +
##Automatic re-validation after a time period! in ProxyValidator.
Needed infos for passed by config

- reschedule pattern
- amount of taken proxies


@TASK:{counter:task} 20170715 +
CLI Test


@TASK:{counter:task} 20170715 +
Impl. Loader which initialize and handles the lifecycle of
components (starts up, shutdown, dii) in the app. Or call it
maybe AppLoader.

* static Config and Logger
* Storage


@TASK:{counter:task} 20170715 +
Extend commons-config by

* parse single arguments, impl. seperate handler for this
* parse json config

This must be moved to the package task queue.


[.line-through]#@TASK:{counter:task} 20170716# +
Impl. IProxyValidatorOptions


[.line-through]#@TASK:{counter:task} 20170717# +minor +
Impl. proxy rotation mechanism for proxy server. On request the fastest in line
proxy should be used for new connection. The request can also contain multiple
selection headers.

 Proxy-Select-Level: <number>
 Proxy-Select-Country: <ISO-9601>
 Proxy-Select-Speed-Limit: <milliseconds>
 Proxy-Select-SSL: <true|false>
 Proxy-Select-Fallback: <true|false>

When criteria don't match then a bad response is created with
the appropriate error message, but only when fallback is false.


@TASK:{counter:task} 20170718 +
Testing proxies for abilities of websocket, ..., other


[.line-through]#@TASK:{counter:task} 20170727# +
Remove or correct log message

* Error messages should be thrown on errors
* Single message line in useless methods
* Refactor content of log messages


@TASK:{counter:task} 20170727 +
On Ctrl+C kill all running tasks (validator; manager)

@TASK:{counter:task} 20170727 +
Impl. options for proxy filter, currently multiple fields are set
static.

@TASK:{counter:task} 20170727 +
Impl. timeout for judge selftest on startup. If no response is received
then the system stucks (blocking firewall!).

@TASK:{counter:task} 20170728 +
Verify that proxies selected by the validator for recheck are ignored
when a recheck was already ordered. (extend table)

@TASK:{counter:task} 20170728 +
Add bash startup scripts in bin directory.